# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dannygb-meter-readings

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_313d6458310141de9a06ae1ffa39a99c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3d19f6b8c7e540c8bb02436ff476dee1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_313d6458310141de9a06ae1ffa39a99c }}/meterui:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dannygb-meter-readings'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_31414e82f70548138da59611daaeec05 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_313d6458310141de9a06ae1ffa39a99c }}/meterui:${{ github.sha }}'